version: "3.9"
services:
  api:
    image: api
    build:
      context: .
      dockerfile: ./src/PurchaseOrderProcessor.Api/Dockerfile
    ports:
      - 5000:80
      - 5443:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+